language: generic 
docksudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t keiseithunder/learn-docker-react .

script:
  - docker run -e CI=true keiseithunder/learn-docker-react npm run test