language: generic 
docksudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t keiseithunder/learn-docker-react .

script:
  - docker run -e CI=true keiseithunder/learn-docker-react npm run 
  
deploy:
  provide: elasticbeanstalk
  region: "ap-southeast-1"
  app: "learn-docker-react"
  env: "LearnDockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-419618831002"
  bucket_path: "learn-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
